version: 2

before:
  hooks:
    - go mod tidy
builds:
  - binary: sacloud-cpu-usage
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: '{{ .ProjectName }}_SHA256SUMS'
  algorithm: sha256

changelog:
  disable: false
  filters:
    exclude:
      - '^docs:'